[package]
name = "ggml-io"
version = "0.1.0"
edition = "2021"

[lib]
name = "ggml_io"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }